/* Generated By:JavaCC: Do not edit this line. FOLGrammarConstants.java */
package POMA.Verification.ReachabilityAnalysis.FOLparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FOLGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 5;
  /** RegularExpression Id. */
  int CLOSE = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int QUESTION = 8;
  /** RegularExpression Id. */
  int PERMIT = 9;
  /** RegularExpression Id. */
  int DENY = 10;
  /** RegularExpression Id. */
  int EXPLICITASSIGN = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int ASSOCIATE = 13;
  /** RegularExpression Id. */
  int HIERARCHY = 14;
  /** RegularExpression Id. */
  int OBLIGATIONLABEL = 15;
  /** RegularExpression Id. */
  int EXISTS = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int CONST = 20;
  /** RegularExpression Id. */
  int VAR = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"?\"",
    "\"PERMIT\"",
    "\"DENY\"",
    "\"EXPLICITASSIGN\"",
    "\"ASSIGN\"",
    "\"ASSOCIATE\"",
    "\"HIERARCHY\"",
    "\"OBLIGATIONLABEL\"",
    "\"EXISTS\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "<CONST>",
    "<VAR>",
    "<IDENTIFIER>",
    "\";\"",
  };

}
